---
theme: jekyll-theme-minimal
title: Quoc Huy Do's CV
description: "âœ‰Email: quoc_huydo2003@outlook.com <br> ğŸ“TÃ©lÃ©phone: +1 438-630-5632 <br> ğŸ’¬Langues:ğŸ‡ºğŸ‡¸ ğŸ‡«ğŸ‡· ğŸ‡»ğŸ‡³ <br> ğŸ“Laval, QuÃ©bec"
