---
theme: jekyll-theme-minimal
title: Quoc Huy Do's CV
description: "âœ‰Email: quoc_huydo2003@outlook.com <br> ğŸ“TÃ©lÃ©phone: +1
  438-630-5632 <br> ğŸ’¬Langues:ğŸ‡ºğŸ‡¸ ğŸ‡«ğŸ‡· ğŸ‡»ğŸ‡³ <br> ğŸ“Laval, QuÃ©bec"

---
title: Ã‰ducation
Subtitle: CollÃ¨ge Montmorency
Date: 2021-2024
Description: Ã‰tudiÃ© en Technique d'IntÃ©gration MultimÃ©dia, un programme qui
  enseigne le domaine du multimÃ©dia en gÃ©nÃ©ral.
